name: Deploy CRA to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if different

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use your preferred Node version

    - name: Install dependencies
      run: npm ci

    - name: Build the React app
      env:
        CI: false
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./build

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1  # Official GitHub action for Pages deployment
      with:
        publish_dir: ./build