name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Change to project directory
      run: cd flying-comet-homepage

    - name: Install dependencies
      working-directory: ./flying-comet-homepage
      run: npm ci

    - name: Build
      working-directory: ./flying-comet-homepage
      env:
        CI: false
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./flying-comet-homepage/build
